### ISSUE TITLE
[Bug] 'Add/Remove from library' closes browser tab in Firefox Private window

### ISSUE THREAD

**Issue by 4rnv** [NusryNizam/yewdio-app#1]
Browser: Firefox 111.0
OS: Windows  10
Description: 

1. Open yewdio.vercel.app in Firefox private window. 
2. Select a song and press add to favourites.
3. Select add to library from favourites section, the window closes automatically.
4. Upon restoring the window through Ctrl+Shift+T, it seems that the song does get added to library. However the window closes for whatever reason.
5. Problem is not replicated in Firefox's normal window or on Chromium based browsers.

I suspect this may have something to do with Firefox not supporting service workers in Private windows (ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1320796). Nevertheless, the window closing unexpectedly is something that could be fixed through exception handling.

**Comment by NusryNizam** [comment]
Thanks for the report. However, i couldn't reproduce it on Firefox on Windows 11 or Linux. I added an ErrorBoundary component to handle the error. Hope it fixes the crashing issue.
